#!/usr/bin/env bash
set -u

CODEX_TERMUX_COMPAT_DIR="${BASH_SOURCE[0]%/*}"
[ "$CODEX_TERMUX_COMPAT_DIR" = "${BASH_SOURCE[0]}" ] && CODEX_TERMUX_COMPAT_DIR="."
CODEX_TERMUX_COMPAT_DIR="$(cd "$CODEX_TERMUX_COMPAT_DIR" && pwd)"
CODEX_TERMUX_COMPAT_ROOT="$(cd "$CODEX_TERMUX_COMPAT_DIR/.." && pwd)"

if [ -r "$CODEX_TERMUX_COMPAT_DIR/shell/loader.sh" ]; then
    CODEX_TERMUX_WRAPPER_ROOT="${CODEX_TERMUX_WRAPPER_ROOT:-$CODEX_TERMUX_COMPAT_DIR}"
    # shellcheck disable=SC1091
    . "$CODEX_TERMUX_COMPAT_DIR/shell/loader.sh"
elif [ -r "$CODEX_TERMUX_COMPAT_ROOT/shell/loader.sh" ]; then
    CODEX_TERMUX_WRAPPER_ROOT="${CODEX_TERMUX_WRAPPER_ROOT:-$CODEX_TERMUX_COMPAT_ROOT}"
    # shellcheck disable=SC1091
    . "$CODEX_TERMUX_COMPAT_ROOT/shell/loader.sh"
else
    CODEX_TERMUX_SHELL_DIR="$CODEX_TERMUX_COMPAT_DIR"

    CODEX_TERMUX_HOME="${CODEX_TERMUX_HOME:-$HOME}"
    CODEX_TERMUX_PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
    CODEX_TERMUX_ROOT="${CODEX_TERMUX_ROOT:-$CODEX_TERMUX_HOME/.local/lib/codex/termux}"
    CODEX_TERMUX_MANAGER_DIR="${CODEX_TERMUX_MANAGER_DIR:-$CODEX_TERMUX_ROOT/manager}"
    CODEX_TERMUX_SOURCE_DIR="${CODEX_TERMUX_SOURCE_DIR:-$CODEX_TERMUX_MANAGER_DIR/source}"
    CODEX_TERMUX_RAW_DIR="${CODEX_TERMUX_RAW_DIR:-$CODEX_TERMUX_ROOT/raw}"
    CODEX_TERMUX_RAW_VENDOR="${CODEX_TERMUX_RAW_VENDOR:-$CODEX_TERMUX_RAW_DIR/vendor/aarch64-unknown-linux-musl}"
    CODEX_TERMUX_RUNTIME_DIR="${CODEX_TERMUX_RUNTIME_DIR:-$CODEX_TERMUX_ROOT/current}"
    CODEX_TERMUX_CURRENT_LINK="${CODEX_TERMUX_CURRENT_LINK:-$CODEX_TERMUX_RUNTIME_DIR}"
    CODEX_TERMUX_VERIFIED_LINK="${CODEX_TERMUX_VERIFIED_LINK:-$CODEX_TERMUX_ROOT/verified}"
    CODEX_TERMUX_RUNTIME="${CODEX_TERMUX_RUNTIME:-$CODEX_TERMUX_RUNTIME_DIR/codex}"
    CODEX_TERMUX_MANAGED_SHELL="${CODEX_TERMUX_MANAGED_SHELL:-$CODEX_TERMUX_MANAGER_DIR/managed.sh}"
    CODEX_TERMUX_STATE_DIR="${CODEX_TERMUX_STATE_DIR:-$CODEX_TERMUX_HOME/.local/share/codex/termux}"
    CODEX_TERMUX_PROFILE_ROOT="${CODEX_TERMUX_PROFILE_ROOT:-$CODEX_TERMUX_HOME/.codex-profiles}"
    CODEX_TERMUX_STATE_FILE="${CODEX_TERMUX_STATE_FILE:-$CODEX_TERMUX_STATE_DIR/state.json}"
    CODEX_TERMUX_REGISTRY_FILE="${CODEX_TERMUX_REGISTRY_FILE:-$CODEX_TERMUX_STATE_DIR/registry.json}"
    CODEX_TERMUX_STORE_DIR="${CODEX_TERMUX_STORE_DIR:-$CODEX_TERMUX_ROOT/store}"
    CODEX_TERMUX_RUNTIME_STORE_DIR="${CODEX_TERMUX_RUNTIME_STORE_DIR:-$CODEX_TERMUX_STORE_DIR/runtime}"
    CODEX_TERMUX_RAW_STORE_DIR="${CODEX_TERMUX_RAW_STORE_DIR:-$CODEX_TERMUX_STORE_DIR/raw}"
    CODEX_TERMUX_BACKUP_DIR="${CODEX_TERMUX_BACKUP_DIR:-$CODEX_TERMUX_STATE_DIR/backups}"
    CODEX_TERMUX_DOCTOR_DIR="${CODEX_TERMUX_DOCTOR_DIR:-$CODEX_TERMUX_STATE_DIR/doctor}"
    CODEX_TERMUX_LOCK_FILE="${CODEX_TERMUX_LOCK_FILE:-$CODEX_TERMUX_STATE_DIR/termux.lock}"
    CODEX_TERMUX_LOCK_WAIT_SECONDS="${CODEX_TERMUX_LOCK_WAIT_SECONDS:-30}"
    CODEX_TERMUX_RESOLV_CONF="${CODEX_TERMUX_RESOLV_CONF:-$CODEX_TERMUX_PREFIX/etc/resolv.conf}"
    CODEX_TERMUX_TMPDIR="${CODEX_TERMUX_TMPDIR:-$CODEX_TERMUX_PREFIX/tmp}"
    CODEX_TERMUX_SYSTEM_CONFIG_DIR="${CODEX_TERMUX_SYSTEM_CONFIG_DIR:-$CODEX_TERMUX_STATE_DIR/system-config}"
    CODEX_TERMUX_TURN_NOTIFY="${CODEX_TERMUX_TURN_NOTIFY:-$CODEX_TERMUX_MANAGER_DIR/codex-turn-notify.sh}"
    CODEX_TERMUX_NOTIFY_DIR="${CODEX_TERMUX_NOTIFY_DIR:-$CODEX_TERMUX_STATE_DIR/notify}"
    CODEX_TERMUX_NOTIFY_CONFIG="${CODEX_TERMUX_NOTIFY_CONFIG:-$CODEX_TERMUX_NOTIFY_DIR/config.env}"
    CODEX_TERMUX_NOTIFY_GROUP="${CODEX_TERMUX_NOTIFY_GROUP:-codex-turns}"
    CODEX_TERMUX_NOTIFY_CONTENT_CHARS="${CODEX_TERMUX_NOTIFY_CONTENT_CHARS:-0}"
    CODEX_TERMUX_NOTIFY_PRESERVE_NEWLINES="${CODEX_TERMUX_NOTIFY_PRESERVE_NEWLINES:-1}"
    CODEX_TERMUX_NOTIFY_TOAST_SHORT="${CODEX_TERMUX_NOTIFY_TOAST_SHORT:-0}"
    CODEX_TERMUX_NOTIFY_TOAST_DURATION="${CODEX_TERMUX_NOTIFY_TOAST_DURATION:-}"
    CODEX_TERMUX_NOTIFY_TOAST_BACKGROUND="${CODEX_TERMUX_NOTIFY_TOAST_BACKGROUND:-}"
    CODEX_TERMUX_NOTIFY_TOAST_COLOR="${CODEX_TERMUX_NOTIFY_TOAST_COLOR:-}"
    CODEX_TERMUX_NOTIFY_PRETOOLUSE="${CODEX_TERMUX_NOTIFY_PRETOOLUSE:-0}"
    CODEX_TERMUX_NOTIFY_HOOKS="${CODEX_TERMUX_NOTIFY_HOOKS:-Stop}"
    CODEX_TERMUX_NOTIFY_TOAST_GRAVITY="${CODEX_TERMUX_NOTIFY_TOAST_GRAVITY:-top}"
    CODEX_TERMUX_CERT_FILE="${CODEX_TERMUX_CERT_FILE:-$CODEX_TERMUX_PREFIX/etc/tls/cert.pem}"
    CODEX_TERMUX_CERT_DIR="${CODEX_TERMUX_CERT_DIR:-$CODEX_TERMUX_PREFIX/etc/tls/certs}"
    CODEX_TERMUX_PACKAGE_SPEC_DEFAULT="${CODEX_TERMUX_PACKAGE_SPEC_DEFAULT:-@openai/codex@linux-arm64}"
    CODEX_TERMUX_MANAGED_LAUNCHER_MARKER="${CODEX_TERMUX_MANAGED_LAUNCHER_MARKER:-codex termux managed launcher}"
    CODEX_TERMUX_PUBLIC_CODEX="${CODEX_TERMUX_PUBLIC_CODEX:-$CODEX_TERMUX_PREFIX/bin/codex}"
    CODEX_TERMUX_RUNTIME_BUILDER="${CODEX_TERMUX_RUNTIME_BUILDER:-$CODEX_TERMUX_MANAGER_DIR/build-runtime.py}"
    CODEX_TERMUX_AUTO_UPDATE="${CODEX_TERMUX_AUTO_UPDATE:-1}"
    CODEX_TERMUX_AUTO_UPDATE_MODE="${CODEX_TERMUX_AUTO_UPDATE_MODE:-prompt}"
    CODEX_TERMUX_AUTO_UPDATE_INTERVAL_SECONDS="${CODEX_TERMUX_AUTO_UPDATE_INTERVAL_SECONDS:-21600}"
    CODEX_TERMUX_AUTO_UPDATE_TIMEOUT_SECONDS="${CODEX_TERMUX_AUTO_UPDATE_TIMEOUT_SECONDS:-4}"
    CODEX_TERMUX_AUTO_UPDATE_STAMP="${CODEX_TERMUX_AUTO_UPDATE_STAMP:-$CODEX_TERMUX_STATE_DIR/last-auto-update-check}"
    CODEX_TERMUX_AUTO_UPDATE_PENDING="${CODEX_TERMUX_AUTO_UPDATE_PENDING:-$CODEX_TERMUX_STATE_DIR/pending-auto-update-version}"
    CODEX_TERMUX_AUTO_UPDATE_FAILED="${CODEX_TERMUX_AUTO_UPDATE_FAILED:-$CODEX_TERMUX_STATE_DIR/failed-auto-update}"
    CODEX_TERMUX_UPSTREAM_TIME_CACHE="${CODEX_TERMUX_UPSTREAM_TIME_CACHE:-$CODEX_TERMUX_STATE_DIR/upstream-time-cache.tsv}"
    CODEX_TERMUX_LAST_PROFILE_FILE="${CODEX_TERMUX_LAST_PROFILE_FILE:-$CODEX_TERMUX_STATE_DIR/last-profile}"
    CODEX_TERMUX_RUNTIME_RETENTION="${CODEX_TERMUX_RUNTIME_RETENTION:-3}"
    CODEX_TERMUX_PATCH_POLICY="${CODEX_TERMUX_PATCH_POLICY:-termux-fd-remap-v1}"
    CODEX_TERMUX_WRAPPER_SOURCE_CONFIG="${CODEX_TERMUX_WRAPPER_SOURCE_CONFIG:-$CODEX_TERMUX_HOME/.config/codex-termux/wrapper-source.env}"

    CODEX_STATUS_ACTIVE=0
    CODEX_TERMUX_SHELL_LIB="${CODEX_TERMUX_SHELL_LIB:-$CODEX_TERMUX_SHELL_DIR/${BASH_SOURCE[0]##*/}}"
    CODEX_TERMUX_WRAPPER_ROOT="${CODEX_TERMUX_WRAPPER_ROOT:-$CODEX_TERMUX_COMPAT_ROOT}"

    codex_source_domain() {
        local path="$CODEX_TERMUX_SHELL_DIR/codex-termux/$1.sh"
        [ -r "$path" ] || {
            printf 'ERROR: missing Codex Termux wrapper domain: %s\n' "$path" >&2
            return 1
        }
        # shellcheck disable=SC1090
        . "$path"
    }

    for CODEX_TERMUX_DOMAIN in state ui fs prompt exec store build runtime repair version notify doctor profile use remove session dispatch; do
        codex_source_domain "$CODEX_TERMUX_DOMAIN" || return $?
    done
    unset CODEX_TERMUX_DOMAIN
fi

unset CODEX_TERMUX_COMPAT_DIR CODEX_TERMUX_COMPAT_ROOT
